### ISSUE TITLE
The listing doesn't use fieldtype specific components

### ISSUE THREAD

**Issue by riasvdv** [doublethreedigital/runway#52]
### Description

The data is rendered just "as-is". For example a date field gets rendered like this in collections:

![image](https://user-images.githubusercontent.com/3626559/124624316-133d6100-de7d-11eb-87ba-8053088caa7f.png)

But in runway it's like this:

![image](https://user-images.githubusercontent.com/3626559/124624387-1df7f600-de7d-11eb-843b-1c5560a8c3fe.png)

### Environment

Statamic 3.1.26 Pro
Laravel 8.49.0
PHP 8.0.6
doublethreedigital/runway 2.1.0

**Comment by duncanmcclean** [comment]
Thanks for pointing that out! We probably need to use `preProcessIndex` instead of just grabbing the value directly from Eloquent.

**Comment by duncanmcclean** [comment]
This is fixed in [v2.2.1](https://github.com/doublethreedigital/runway/releases/tag/v2.1.1). Have a great rest of your day!

**Comment by riasvdv** [comment]
🚀 such speed!

**Comment by riasvdv** [comment]
So, it's not completely solved yet it seems. It's still using the <DefaultField> components for the index listing (it should be using a CurrencyFieldtypeIndex here):

<img width="278" alt="image" src="https://user-images.githubusercontent.com/3626559/124718508-73c4b080-df06-11eb-8241-4683c064d344.png">

The collections listing uses the following for custom fieldtypes:

<img width="363" alt="image" src="https://user-images.githubusercontent.com/3626559/124718243-306a4200-df06-11eb-9403-c2dad9794000.png">

**Comment by duncanmcclean** [comment]
Re-opened and I'll take a look this evening - didn't know they actually had different Vue components depending on the fieltype 😆

**Comment by duncanmcclean** [comment]
Now it should be fixed properly, in [v2.1.2](https://github.com/doublethreedigital/runway/releases/tag/v2.1.2). Tested with your color swatches addon and it worked great (nice addon btw).
